# Generated by Django 2.1.3 on 2019-11-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
