# Generated by Django 2.1.3 on 2019-11-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_weather', '0002_auto_20191105_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
